# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json

version: '2'

run:
  allow-parallel-runners: true

linters:
  default: none
  enable:
    - asasalint
    - bidichk
    - bodyclose
    - canonicalheader
    - copyloopvar
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - fatcontext
    - gocheckcompilerdirectives
    - goprintffuncname
    - govet
    - grouper
    - inamedparam
    - ineffassign
    - intrange
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nolintlint
    - paralleltest
    - predeclared
    - reassign
    - testableexamples
    - tparallel
    - unconvert
    - usestdlibvars
    - usetesting

  exclusions:
    presets:
      - comments
      - std-error-handling

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
